name: transformer_env
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pytorch
  - torchvision
  - numpy
  - pandas
  - matplotlib
  - jupyter
  - pip
  - pip:
    - transformers
    - tensorboard
    - tqdm